apiVersion: v2
name: common-test
description: Helper chart to test different use cases of the common library
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords:
- blissflow
- common
home: https://github.com/blissflow-tech/library-charts/tree/main/helper-charts/common-test
maintainers:
- name: amos-85
  email: contact@blissflow.tech
dependencies:
- name: common
  repository: file://../../charts/stable/common
  version: "*"
