apiVersion: v2
name: common
description: Function library for blissflow charts
type: library
version: 4.10.0
kubeVersion: ">=1.16.0-0"
keywords:
- blissflow
- common
home: https://github.com/blissflow/library-charts/tree/main/stable/common
maintainers:
- name: amos-85
  email: contact@blissflow.tech
